# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93e71a879d754b50535075bc6632883d2c4cd1e27f5fa0db20486d0f9fd9dd6a54b6825ca15423d54e0e72c82af7fd075bf55d98d25c73fa2091320aa860c817

test:
  secret_key_base: e46b8806b3d62ef8e2a80b1874b88963f32afbe863e5af0fe16214b4d5b4d8ccff025dbbb97416ace43b0cb7bde898de697a60a923c1f0ae8f327d77c3508aba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
